[package]
name = "ec_arithmetic"
version = "0.1.0"
authors = ["Iszak Bryan <38895+iszak@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
